In [2]:
import torch

/usr/local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [32]:
a = torch.tensor([[1,2], [3,4]])
a

tensor([[1, 2],
        [3, 4]])

In [38]:
b = torch.tensor([[1]])
b

tensor([[1]])

In [41]:
a+b

tensor([[2, 3],
        [4, 5]])

In [40]:
print(b.stride(), b.broadcast_to(a.shape).stride())


(1, 1) (0, 0)


Rule seems to be that whatever dimension we broadcast over, the new stride is 0.
And we have to add extra dimensions somehow which I don't know yet.   

In [65]:
b.expand((2, 2))

tensor([[1, 1],
        [1, 1]])

In [67]:
b.expand((2, 2)) + a

tensor([[2, 3],
        [4, 5]])

Interesting squeeze, removes all 1 dimensions. Or specified one.

In [82]:
b.expand((1, 2,1,2, 1)).squeeze().shape

torch.Size([2, 2])

In [83]:
b.expand((1, 2,1,2, 1)).squeeze(0).shape

torch.Size([2, 1, 2, 1])

In [86]:
print(b.stride())
print(b.expand(2,2).stride())
print(b.expand(2,2, 1).stride())
print(b.expand(2,2, 1).squeeze().stride())

(1, 1)
(0, 0)
(0, 0, 1)
(0, 0)


In [108]:
print(b.stride())
print(b.expand(2,2).stride())
print(b.expand(2,0, 2, 1).stride())

(1, 1)
(0, 0)
(0, 0, 0, 1)


In [110]:
d = torch.tensor([[1,2]])
d.expand((2,2))

tensor([[1, 2],
        [1, 2]])

In [117]:
torch.tensor(5).expand(a.shape).stride()

(0, 0)

In [120]:
torch.tensor(5).expand((2,1)).stride()

(0, 0)