In [17]:
import torch

/usr/local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [18]:
a = [1,2,3,4,5,6]
b = [0,1,2,3,4,5]

A = torch.tensor(a).reshape(2,3)
B = torch.tensor(b).reshape(3,2)

In [19]:
A

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
B

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [21]:
A@B

tensor([[16, 22],
        [34, 49]])

In [22]:
print(A[0, :] @ B)
print(A[1, :] @ B)

tensor([16, 22])
tensor([34, 49])


Expand B so that it repeats itself

In [23]:
A.shape

torch.Size([2, 3])

In [52]:
(A.reshape(2,3,1).broadcast_to(2,3,2)*B.reshape(1,3,2).broadcast_to(2,3,2)).sum(1)

tensor([[16, 22],
        [34, 49]])

In [53]:
import numpy as np
def custom_matmul(A, B):
    # Expand dimensions to prepare for broadcasting
    expanded_A = A[:, :, np.newaxis]  # Shape: (m, n, 1)
    expanded_B = B[np.newaxis, :, :]  # Shape: (1, n, p)
    
    # Element-wise multiplication (broadcasted)
    product = expanded_A * expanded_B  # Shape: (m, n, p)
    
    # Sum over the shared dimension (n)
    result = product.sum(axis=1)      # Shape: (m, p)
    
    return result

custom_matmul(np.array(a).reshape(2,3), np.array(b).reshape(3,2))

array([[16, 22],
       [34, 49]])