In [1]:
import numpy as np

In [19]:
a = np.arange(0,8).reshape((2,2,2))
print(a.reshape(-1))
print(a)

[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [58]:
strides = [4,1,2]
shape = [2,2,2]
def offset(gidx, strides, shape):
	i = np.floor(gidx / 2)
	j = gidx % 2
	return int(i),int(j), 0)

for i in range(4):
	print(offset(i, strides, shape))

#  (0, 0, 0)
#  (0, 1, 0)
#  (1, 0, 0)
#  (1, 1, 0)


(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)


In [61]:
def strides(a):
	res = np.array(a.strides)/ (a.nbytes / np.array(a.shape).prod())
	return tuple(int(i) for i in res)
a = np.arange(0,12).reshape((2,3,2))
print(a.reshape(-1))
print(a)
print(strides(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(6, 2, 1)


In [63]:
strides = [6,1,2]
shape = [2,3,2]
def offset(gidx, strides, shape):
	i = np.floor(gidx / shape[0])
	j = gidx % shape[1]
	return (int(i),int(j), 0)

for i in range(6):
	print(offset(i, strides, shape))


(0, 0, 0)
(0, 1, 0)
(1, 2, 0)
(1, 0, 0)
(2, 1, 0)
(2, 2, 0)


In [65]:
def strides(a):
	res = np.array(a.strides)/ (a.nbytes / np.array(a.shape).prod())
	return tuple(int(i) for i in res)
a = np.arange(0,16).reshape((2,2,2,2))
print(a.reshape(-1))
print(a)
print(strides(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
(8, 4, 2, 1)


In [87]:
strides = [8,4,1,2]
shape = [2,2,2,2]
def offset(gidx, strides, shape):
	i = np.floor(gidx / shape[0] / shape[1]) % shape[0]
	j = np.floor(gidx / shape[0]) % shape[1]
	k = np.floor(gidx) % shape[2]
	f = lambda x: f"[{int(x)}]"
	return f(i) + f(j) + f(k) + f(0)

for i in range(8):
	print(i, offset(i, strides, shape))

print("vs actual")

print(0, "[0][0][0][0]")
print(1, "[0][0][1][0]")
print(2, "[0][1][0][0]")
print(3, "[0][1][1][0]")
print(4, "[1][0][0][0]")
print(5, "[1][0][1][0]")
print(6, "[1][1][0][0]")
print(7, "[1][1][1][0]")


0 [0][0][0][0]
1 [0][0][1][0]
2 [0][1][0][0]
3 [0][1][1][0]
4 [1][0][0][0]
5 [1][0][1][0]
6 [1][1][0][0]
7 [1][1][1][0]
vs actual
0 [0][0][0][0]
1 [0][0][1][0]
2 [0][1][0][0]
3 [0][1][1][0]
4 [1][0][0][0]
5 [1][0][1][0]
6 [1][1][0][0]
7 [1][1][1][0]


In [141]:
def offset_general(gidx, strides, shape):
    indices = [-1 for _ in range(len(shape)-1)]
    v=gidx
    for i in range(len(indices)):
        bi = len(shape)-i-2
        if i > 0:
            v /= shape[i-1]
        indices[bi]  = np.floor(v) % shape[bi]

    s = ""
    for i in indices:
        f = lambda x: f"[{int(x)}]"
        s+= f(i)
    s+= f(0)
    print(s)


for i in range(8):
    offset_general(i, strides, shape)

[0][0][0][0]
[0][0][1][0]
[0][0][0][0]
[0][0][1][0]
[0][1][0][0]
[0][1][1][0]
[0][1][0][0]
[0][1][1][0]


In [142]:
b = np.arange(16).reshape(4,2,1,2)
b

array([[[[ 0,  1]],

        [[ 2,  3]]],


       [[[ 4,  5]],

        [[ 6,  7]]],


       [[[ 8,  9]],

        [[10, 11]]],


       [[[12, 13]],

        [[14, 15]]]])

In [143]:
def strides(a):
	res = np.array(a.strides)/ (a.nbytes / np.array(a.shape).prod())
	return tuple(int(i) for i in res)

In [173]:
stride = (4,2,1,2)
shape = (4,2,2,1)


for gid in range(8):
	i = gid%4
	j = (gid//4)%2
	k = (gid//2)%2
	print(i, j, k, 0)

0 0 0 0
1 0 0 0
2 0 1 0
3 0 1 0
0 1 0 0
1 1 0 0
2 1 1 0
3 1 1 0


In [176]:
stride = (4,2,1,2)
shape = (4,2,1,2)


for gid in range(8):
	i = gid%4
	j = (gid//4)%2
	k = (gid//2)%1
	print(i, j, k, 0)

0 0 0 0
1 0 0 0
2 0 0 0
3 0 0 0
0 1 0 0
1 1 0 0
2 1 0 0
3 1 0 0
