In [1]:
import torch

/usr/local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [19]:
n = 5
x = torch.tensor([0,1,2,3,4], dtype=torch.float32, requires_grad=True).reshape((n,1))
w = torch.tensor([0], dtype=torch.float32, requires_grad=True).reshape((1,1))
x.retain_grad()
w.retain_grad()
print(x)
print(w)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]], grad_fn=<ReshapeAliasBackward0>)
tensor([[0.]], grad_fn=<ReshapeAliasBackward0>)


In [20]:
summed = (x@w).sum(0)*(1/5)
summed.backward()


print(w.grad)
print(x.grad)

tensor([[2.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])
