In [8]:
import numpy as np

def strides(a):
	res = np.array(a.strides)/ (a.nbytes / np.array(a.shape).prod())
	return tuple(int(i) for i in res)

In [44]:
A = np.arange(8).reshape((2,2,2))
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
AT = A.transpose([0, 2, 1])
AT

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [46]:
ATR = AT.reshape(-1, 2)
ATR

array([[0, 2],
       [1, 3],
       [4, 6],
       [5, 7]])

In [47]:
AT[0][0][0] = 1
ATR

array([[0, 2],
       [1, 3],
       [4, 6],
       [5, 7]])

In [48]:
AT

array([[[1, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [51]:
ATR.flags.contiguous

True

In [52]:
B = A.copy()
B

array([[[1, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
BT = B.T
BT.flags.contiguous

False

In [55]:
BT.reshape(4,2).flags.contiguous

True

In [14]:
a = [i for i in range(8)]
a

[0, 1, 2, 3, 4, 5, 6, 7]

In [18]:
shape = [2,2,2]
stride = [4,2,1]

for i in range(shape[0]):
	for j in range(shape[1]):
		for k in range(shape[2]):
			idx = i*stride[0] + j*stride[1] + k*stride[2]
			print(a[idx], end=" ")
		print()
	print()

0 1 
2 3 

4 5 
6 7 



In [19]:
# T
stride = [4,1,2]
for i in range(shape[0]):
	for j in range(shape[1]):
		for k in range(shape[2]):
			idx = i*stride[0] + j*stride[1] + k*stride[2]
			print(a[idx], end=" ")
		print()
	print()

0 2 
1 3 

4 6 
5 7 



In [20]:
shape = [4,2]
stride = [2, 1]
for i in range(shape[0]):
	for j in range(shape[1]):
		idx = i*stride[0] + j*stride[1]
		print(a[idx], end=" ")
	print()

0 1 
2 3 
4 5 
6 7 
