In [3]:
import torch

/usr/local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
a = torch.tensor([[1, 0, -1]], dtype=torch.float32, requires_grad=True)

In [5]:
a.retain_grad()

In [10]:
b = a.softmax(-1)
b.retain_grad()
c = b.sum(-1)
c.retain_grad()
c.backward()

In [11]:
print(a.grad)
print(b.grad)
print(c.grad)

tensor([[0., 0., 0.]])
tensor([[1., 1., 1.]])
tensor([1.])
