In [1]:
import numpy as np

In [46]:
def strides(a):
	res = np.array(a.strides)/ (a.nbytes / np.array(a.shape).prod())
	return tuple(int(i) for i in res)

In [47]:
a = np.arange(1, 9, dtype=np.float32).reshape((2,2,2))
print(a, strides(a))

[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]] (4, 2, 1)


In [48]:
print(a.sum(axis=0, keepdims=True))
print(strides(a.sum(axis=0, keepdims=True)))

[[[ 6.  8.]
  [10. 12.]]]
(4, 2, 1)


In [49]:
print(a.sum(axis=1, keepdims=True))
print(strides(a.sum(axis=1, keepdims=True)))

[[[ 4.  6.]]

 [[12. 14.]]]
(2, 2, 1)


In [50]:
print(a.sum(axis=-1, keepdims=True))
print(strides(a.sum(axis=-1, keepdims=True)))

[[[ 3.]
  [ 7.]]

 [[11.]
  [15.]]]
(2, 1, 1)


In [61]:
a.transpose((0,2,1))

array([[[1., 3.],
        [2., 4.]],

       [[5., 7.],
        [6., 8.]]], dtype=float32)